I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 877, in script
    show zeil with smile2
  File "game/script.rpy", line 877, in <module>
    show zeil with smile2
NameError: name 'smile2' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 877, in script
    show zeil with smile2
  File "renpy/ast.py", line 1439, in execute
    paired = renpy.python.py_eval(self.paired)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 877, in <module>
    show zeil with smile2
NameError: name 'smile2' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Fursuit of Justice 1.0
Fri May 27 02:55:07 2022
